In [9]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px



import pickle

In [2]:
base_url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"

def loadData(fileName, columnName):
    data = pd.read_csv(base_url + fileName) \
             .melt(id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], var_name='date', value_name=columnName) \
             .fillna('<all>')
    data['date'] = data['date'].astype('datetime64[ns]')
    return data

def usData(fileName, columnName):
    data = pd.read_csv(base_url + fileName) \
             .melt(id_vars=['UID', 'iso2', 'iso3', 'code3', 'FIPS', 'Admin2', 'Province_State',
       'Country_Region', 'Lat', 'Long_', 'Combined_Key'], var_name='date', value_name=columnName) \
             .fillna('<all>')
    # Get names of indexes for which column Age has value 30
    indexNames = data[ data['date'] == 'Population' ].index
    # Delete these row indexes from dataFrame
    data.drop(indexNames , inplace=True)
    return data

In [3]:
# Getting US data
us_data = usData("time_series_covid19_confirmed_US.csv", "Confirmed") \
    .merge(usData("time_series_covid19_deaths_US.csv", "Deaths"))
us_data.head()

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key,date,Confirmed,Deaths
0,16,AS,ASM,16,60,<all>,American Samoa,US,-14.2710,-170.1320,"American Samoa, US",1/22/20,0,0
1,316,GU,GUM,316,66,<all>,Guam,US,13.4443,144.7937,"Guam, US",1/22/20,0,0
2,580,MP,MNP,580,69,<all>,Northern Mariana Islands,US,15.0979,145.6739,"Northern Mariana Islands, US",1/22/20,0,0
3,630,PR,PRI,630,72,<all>,Puerto Rico,US,18.2208,-66.5901,"Puerto Rico, US",1/22/20,0,0
4,850,VI,VIR,850,78,<all>,Virgin Islands,US,18.3358,-64.8963,"Virgin Islands, US",1/22/20,0,0

In [4]:
grouped_states = us_data.groupby([ 'date', 'Province_State', 'FIPS', 'Lat', 'Long_']).agg({'Confirmed': 'max', 'Deaths': 'max'}).reset_index()
grouped_states.head()

      date Province_State  FIPS        Lat      Long_  Confirmed  Deaths
0  1/22/20        Alabama  1001  32.539527 -86.644082          0       0
1  1/22/20        Alabama  1003  30.727750 -87.722071          0       0
2  1/22/20        Alabama  1005  31.868263 -85.387129          0       0
3  1/22/20        Alabama  1007  32.996421 -87.125115          0       0
4  1/22/20        Alabama  1009  33.982109 -86.567906          0       0

In [5]:
# Getting world data
all_data = loadData("time_series_covid19_confirmed_global.csv", "CumConfirmed") \
    .merge(loadData("time_series_covid19_deaths_global.csv", "CumDeaths"))
all_data.head()

,Province/State,Country/Region,Lat,Long,date,CumConfirmed,CumDeaths
0,<all>,Afghanistan,33.0000,65.0000,2020-01-22,0,0
1,<all>,Albania,41.1533,20.1683,2020-01-22,0,0
2,<all>,Algeria,28.0339,1.6596,2020-01-22,0,0
3,<all>,Andorra,42.5063,1.5218,2020-01-22,0,0
4,<all>,Angola,-11.2027,17.8739,2020-01-22,0,0

In [6]:
grouped_countries = all_data.groupby(['date','Country/Region', 'Province/State', 'Lat', 'Long']).agg({'CumConfirmed': 'max', 'CumDeaths': 'max'}).reset_index()
grouped_countries.head()

,date,Country/Region,Province/State,Lat,Long,CumConfirmed,CumDeaths
0,2020-01-22,Afghanistan,<all>,33.0000,65.0000,0,0
1,2020-01-22,Albania,<all>,41.1533,20.1683,0,0
2,2020-01-22,Algeria,<all>,28.0339,1.6596,0,0
3,2020-01-22,Andorra,<all>,42.5063,1.5218,0,0
4,2020-01-22,Angola,<all>,-11.2027,17.8739,0,0

In [7]:
# Opening pickled dictionary with demographics data of percentage of population over 65
with open('./pickled_files/age_dict.pkl', 'rb') as f:
    over_65_dict = pickle.load(f)
#over_65_dict

In [8]:
# Opening pickled dictionary with country data
with open('./pickled_files/dev_index_dict.pkl',  'rb') as f:
    dev_index_dict = pickle.load(f)
#dev_index_dict

In [ ]:
# limits = [(0,2),(3,10),(11,20),(21,50),(50,3000)]
# colors = ["royalblue","crimson","lightseagreen","orange","lightgrey"]
# cities = []
# scale = 500

# fig = go.Figure()

# for i in range(len(limits)):
#     lim = limits[i]
# #     df_sub = df[lim[0]:lim[1]]
#     fig.add_trace(go.Scattergeo(
#         locationmode = 'country names',
#         lon = grouped_countries['Long'],
#         lat = grouped_countries['Lat'],
#         text = grouped_countries['CumConfirmed'],
#         marker = dict(
#             size = grouped_countries['CumConfirmed']/scale,
#             color = colors[i],
#             line_color='rgb(40,40,40)',
#             line_width=0.5,
#             sizemode = 'area'
#         ),
#         name = '{0} - {1}'.format(lim[0],lim[1])))

# # fig.update_layout(
# #         title_text = '2014 US city populations<br>(Click legend to toggle traces)',
# #         showlegend = True,
# #         geo = dict(
# #             scope = 'usa',
# #             landcolor = 'rgb(217, 217, 217)',
# #         )
# #     )

# fig.show()

In [ ]:
# fig = go.Figure(data=go.Scattergeo(
#         lon = grouped_countries['Long'],
#         lat = grouped_countries['Lat'],
#         text = grouped_countries['CumConfirmed'],
#         mode = 'markers',

#         marker = dict(
#             size = grouped_countries['CumConfirmed']/200,
#             line_color='rgb(40,40,40)',
#             line_width=0.5,
#             sizemode = 'area'
#         ),
#         ))

# fig.update_layout(
#         geo_scope='world',
#     )
# fig.show()

In [ ]:
fig = go.Figure(data=go.Scattergeo(
        lon = us_data['Long_'],
        lat = us_data['Lat'],
        text = us_data['Deaths'],
        mode = 'markers',

        marker = dict(
            size = us_data['Deaths'],
            line_color='rgb(40,40,40)',
            line_width=0.5,
            sizemode = 'area',
        )
        ))

fig.update_layout(
        title = 'COVID-19 Deaths in the US)',
        geo_scope='usa',
    )
fig.show()

In [18]:
# from urllib.request import urlopen
# import json
# with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
#     counties = json.load(response)
# import plotly.express as px

# fig = px.choropleth(grouped_states, geojson=counties, locations='FIPS', color='Deaths',
#                            color_continuous_scale="Reds",
#                            range_color=(0, 20),
#                            scope="usa",
#                           )
# fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
# fig.show()

In [ ]:
###### fig = px.scatter_geo(grouped_states, locations="Province_State",
#                      locationmode='USA-states',
#                      size="Confirmed",
#                      animation_frame="date",
#                      projection="natural earth")

# # fig.update_layout(
# #         geo = dict(
# #             scope ='usa',
# #         )
# #     )
# fig.show()

In [ ]:
# df = px.data.gapminder()
# fig = px.scatter_geo(grouped_states, locations="FIPS", color="Province_State",
#                      hover_name="Province_State", size="Confirmed",
#                      animation_frame="date",
#                      projection="natural earth")
# fig.show()

In [ ]:
# import csv
# import requests

# CSV_URL = 'http://samplecsvs.s3.amazonaws.com/Sacramentorealestatetransactions.csv'


# with requests.Session() as s:
#     download = s.get(CSV_URL)

#     decoded_content = download.content.decode('utf-8')

#     cr = csv.reader(decoded_content.splitlines(), delimiter=',')
#     my_list = list(cr)
#     for row in my_list:
#         print(row)